# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 31ef78575db2cce5ab0e2643dda5caff6aa57afd2f07947ab07048fbeae9d95d80626b326064b84b0e6666fdac0106702febc6cf859231f0ffd7ea36e86d070b

test:
  secret_key_base: 793956b2629fb1cc8c3bc76c8e3f07a453b602fcaf3d6478ded96680cdee85990242de31832a94716e234539c2797abacc875e842d363bfd713f236a46e4fb49

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
